### ISSUE TITLE
CourseCard.html: Change View/Upcoming/Completed Course to View/Upcoming/Completed echos( )

### ISSUE THREAD

**Issue by wisharya** [frappe/school#237]
Echolearn publishes their videos as **echos** not courses. Is there any to change `View/Upcoming/Completed Course` to `View/Upcoming/Completed echos( )` in [CourseCard.html file](https://github.com/frappe/school/blob/main/community/lms/widgets/CourseCard.html) either by writing a custom script/app? I don't see that file under any doctype, as it is a widget.

Another idea is - If you can make `View/Upcoming/Completed {{ field_name }}` using jinja and add that field in the LMS setting.

Any help/resource to achieve this would be appreciated.

**Comment by pateljannat** [comment]
Reopen if needed
